'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const RAW_DIR = path.join(__dirname, '../../doc/raw');
const ARCHIVE_DIR = path.join(RAW_DIR, 'archive');
const WIKI_DIR = path.join(__dirname, '../../doc/wiki');
const MANIFEST_PATH = path.join(RAW_DIR, 'MANIFEST.sha256');
const INDEX_PATH = path.join(__dirname, '../../doc/index.md');
const LOG_PATH = path.join(__dirname, '../../doc/log.md');

// Helper to calculate SHA-256 of a file
function calculateSHA256(filePath) {
    if (!fs.existsSync(filePath)) return null;
    const fileBuffer = fs.readFileSync(filePath);
    const hashSum = crypto.createHash('sha256');
    hashSum.update(fileBuffer);
    return hashSum.digest('hex');
}

// Read MANIFEST.sha256 into a Map
function readManifest() {
    const manifest = new Map();
    if (!fs.existsSync(MANIFEST_PATH)) return manifest;
    
    const content = fs.readFileSync(MANIFEST_PATH, 'utf8');
    const lines = content.split(/\r?\n/);
    
    for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        
        const spaceIndex = trimmed.indexOf(' ');
        if (spaceIndex !== -1) {
            const hash = trimmed.substring(0, spaceIndex).trim();
            const filePath = trimmed.substring(spaceIndex + 1).trim();
            manifest.set(filePath, hash);
        }
    }
    return manifest;
}

// Recalculate entire raw directory manifest
function updateManifest() {
    console.log('[Verification Agent] Recalculating docs/raw/MANIFEST.sha256...');
    
    const manifestEntries = [];
    
    function walkDir(currentPath, relativePrefix = '') {
        const files = fs.readdirSync(currentPath);
        for (const file of files) {
            const fullPath = path.join(currentPath, file);
            const stat = fs.statSync(fullPath);
            const relPath = relativePrefix ? `${relativePrefix}/${file}` : file;
            
            if (stat.isDirectory()) {
                // Walk subdirectories (like archive, hardware_specs, protocol_logs)
                walkDir(fullPath, relPath);
            } else if (stat.isFile() && file !== 'MANIFEST.sha256') {
                const hash = calculateSHA256(fullPath);
                manifestEntries.push(`${hash}  ${relPath}`);
            }
        }
    }
    
    walkDir(RAW_DIR);
    
    const manifestContent = `# MANIFEST.sha256
# Auto-generated by setup script
${manifestEntries.join('\n')}
`;
    
    fs.writeFileSync(MANIFEST_PATH, manifestContent, 'utf8');
    console.log('[Verification Agent] MANIFEST.sha256 updated successfully.');
}

// Parse Markdown content
function parseMarkdown(content) {
    const frontmatterRegex = /^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/;
    const match = content.match(frontmatterRegex);
    
    let metadata = {};
    let body = '';
    
    if (match) {
        const yamlStr = match[1];
        body = match[2];
        
        const lines = yamlStr.split(/\r?\n/);
        for (const line of lines) {
            const separatorIndex = line.indexOf(':');
            if (separatorIndex !== -1) {
                const key = line.substring(0, separatorIndex).trim();
                const value = line.substring(separatorIndex + 1).trim();
                metadata[key] = value.replace(/^["']|["']$/g, ''); // strip quotes
            }
        }
    } else {
        body = content;
    }
    
    return { metadata, body };
}

// Main logic
function runVerification() {
    console.log('🛡️ [Verification Agent] Starting Evergreens validation and distillation process...');
    
    if (!fs.existsSync(WIKI_DIR)) {
        console.error(`[Verification Agent] ❌ Wiki directory does not exist: ${WIKI_DIR}`);
        return;
    }
    
    const manifestMap = readManifest();
    const files = fs.readdirSync(WIKI_DIR);
    let verifiedCount = 0;
    
    for (const file of files) {
        if (!file.startsWith('draft_') || !file.endsWith('.md')) continue;
        
        const draftPath = path.join(WIKI_DIR, file);
        const draftContent = fs.readFileSync(draftPath, 'utf8');
        const { metadata, body } = parseMarkdown(draftContent);
        
        if (metadata.status !== 'draft') continue;
        
        const originalFileRel = metadata.original_file;
        if (!originalFileRel) {
            console.warn(`[Verification Agent] ⚠️ Draft ${file} does not specify an original raw file. Skipping.`);
            continue;
        }
        
        const originalFilePath = path.join(__dirname, '../../', originalFileRel);
        
        if (!fs.existsSync(originalFilePath)) {
            console.warn(`[Verification Agent] ⚠️ Original file not found for draft ${file}: ${originalFilePath}. Skipping.`);
            continue;
        }
        
        // 1. Integrity Verification (Check SHA-256)
        const currentHash = calculateSHA256(originalFilePath);
        const rawFileNameOnly = path.relative(RAW_DIR, originalFilePath).replace(/\\/g, '/');
        const manifestHash = manifestMap.get(rawFileNameOnly);
        
        if (!manifestHash) {
            console.warn(`[Verification Agent] ⚠️ File ${rawFileNameOnly} is not registered in MANIFEST.sha256!`);
        } else if (currentHash !== manifestHash) {
            console.error(`[Verification Agent] ❌ Hash mismatch for ${rawFileNameOnly}! Calculated: ${currentHash}, Manifest: ${manifestHash}. Skip.`);
            continue;
        } else {
            console.log(`[Verification Agent] Checksum verified: ${rawFileNameOnly} (OK)`);
        }
        
        // 2. Language Verification (Ensure Thai contents)
        const thaiCharRegex = /[\u0e00-\u0e7f]/;
        if (!thaiCharRegex.test(body)) {
            console.warn(`[Verification Agent] ⚠️ Draft ${file} does not contain Thai characters. Distilled content must be in Thai. Skip.`);
            continue;
        }
        
        // 3. Structure Verification
        if (!metadata.title) {
            console.warn(`[Verification Agent] ⚠️ Draft ${file} is missing title in frontmatter. Skip.`);
            continue;
        }
        
        console.log(`[Verification Agent] Verification SUCCESS for draft: ${file}`);
        
        // --- 4. Distill and Promote Draft ---
        // Construct verified metadata frontmatter
        const verifiedMetadata = {
            ...metadata,
            status: 'verified',
            verified_at: new Date().toISOString(),
            verified_by: 'verification_agent'
        };
        delete verifiedMetadata.synthesized_at;
        
        let fmLines = ['---'];
        for (const [key, value] of Object.entries(verifiedMetadata)) {
            fmLines.push(`${key}: "${value}"`);
        }
        fmLines.push('---');
        const newFrontmatter = fmLines.join('\n');
        
        // Remove draft warning note block from body
        let cleanBody = body;
        const noteBlockRegex = />\s*\[!NOTE\][\s\S]*?รอการอนุมัติและตรวจสอบความถูกต้องจาก Verification Agent\r?\n\r?\n/;
        cleanBody = cleanBody.replace(noteBlockRegex, '');
        
        const finalContent = `${newFrontmatter}\n${cleanBody}`;
        const finalFileName = file.replace('draft_', '');
        const finalWikiPath = path.join(WIKI_DIR, finalFileName);
        
        // Save verified evergreen note
        fs.writeFileSync(finalWikiPath, finalContent, 'utf8');
        
        // Delete draft file
        fs.unlinkSync(draftPath);
        
        // Move original raw file to raw/archive
        if (!fs.existsSync(ARCHIVE_DIR)) {
            fs.mkdirSync(ARCHIVE_DIR, { recursive: true });
        }
        const archivePath = path.join(ARCHIVE_DIR, path.basename(originalFilePath));
        fs.renameSync(originalFilePath, archivePath);
        console.log(`[Verification Agent] Moved raw file to archive: ${path.basename(originalFilePath)}`);
        
        // --- 5. Update index.md ---
        if (fs.existsSync(INDEX_PATH)) {
            let indexContent = fs.readFileSync(INDEX_PATH, 'utf8');
            const wikiBaseName = finalFileName.replace('.md', '');
            
            // Check if link already exists in index
            if (!indexContent.includes(`[[wiki/${wikiBaseName}`)) {
                const targetHeader = '## 🗂️ หมวดหมู่ความรู้หลัก (Core Concepts)';
                const headerIndex = indexContent.indexOf(targetHeader);
                if (headerIndex !== -1) {
                    const insertPos = indexContent.indexOf('\n', headerIndex + targetHeader.length + 1);
                    const newLinkLine = `\n- [[wiki/${wikiBaseName}|${verifiedMetadata.title}]] - เอกสารสรุปองค์ความรู้จากการประมวลผลระบบ`;
                    indexContent = indexContent.substring(0, insertPos) + newLinkLine + indexContent.substring(insertPos);
                    fs.writeFileSync(INDEX_PATH, indexContent, 'utf8');
                    console.log(`[Verification Agent] Updated index.md with new link: ${wikiBaseName}`);
                }
            }
        }
        
        // --- 6. Update log.md ---
        if (fs.existsSync(LOG_PATH)) {
            let logContent = fs.readFileSync(LOG_PATH, 'utf8');
            const todayStr = new Date().toISOString().substring(0, 10);
            const logRow = `\n| **${todayStr}** | ทำ Vault Distillation: ตรวจสอบและอนุมัติเอกสาร [[wiki/${finalFileName.replace('.md', '')}|${verifiedMetadata.title}]], ย้ายไฟล์ดิบไป archive | Librarian (Verification Agent) |`;
            
            // Append log row before the end or just at the end of the file
            logContent = logContent.trim() + logRow + '\n';
            fs.writeFileSync(LOG_PATH, logContent, 'utf8');
            console.log('[Verification Agent] Updated log.md.');
        }
        
        verifiedCount++;
    }
    
    // --- 7. Regenerate MANIFEST.sha256 ---
    if (verifiedCount > 0) {
        updateManifest();
    }
    
    console.log(`🛡️ [Verification Agent] Process completed. Verified and distilled ${verifiedCount} files.`);
}

runVerification();
module.exports = { runVerification };
