#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const DOCS_RAW = path.join(__dirname, '..', '..', 'docs', 'raw');
const MANIFEST_PATH = path.join(DOCS_RAW, 'MANIFEST.sha256');

function getSHA256(filepath) {
  const content = fs.readFileSync(filepath);
  return crypto.createHash('sha256').update(content).digest('hex');
}

function generate() {
  console.log('✍️  Starting World Model Manifest Generation...');
  console.log('========================================');

  const files = [];
  function walk(dir) {
    const list = fs.readdirSync(dir);
    for (const item of list) {
      const fullPath = path.join(dir, item);
      const stat = fs.statSync(fullPath);
      if (stat.isDirectory()) {
        walk(fullPath);
      } else {
        const rel = path.relative(DOCS_RAW, fullPath).replace(/\\/g, '/');
        if (rel !== 'MANIFEST.sha256') {
          files.push({ fullPath, rel });
        }
      }
    }
  }

  try {
    walk(DOCS_RAW);
  } catch (err) {
    console.error('❌ Error walking raw directory:', err.message);
    process.exit(1);
  }

  // Sort files by relative path for consistency
  files.sort((a, b) => a.rel.localeCompare(b.rel));

  const lines = [
    '# MANIFEST.sha256',
    '# Auto-generated by setup script'
  ];

  for (const file of files) {
    const hash = getSHA256(file.fullPath);
    lines.push(`${hash}  ${file.rel}`);
    console.log(`✅ Tracked: ${file.rel} (${hash.substring(0, 8)}...)`);
  }

  try {
    fs.writeFileSync(MANIFEST_PATH, lines.join('\n') + '\n', 'utf8');
    console.log('========================================');
    console.log(`🎉 MANIFEST.sha256 successfully generated with ${files.length} files.`);
  } catch (err) {
    console.error('❌ Failed to write MANIFEST.sha256:', err.message);
    process.exit(1);
  }
}

generate();
